---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  USER_NAME: YWRtaW4K
  PASSWORD: MWYyZDFlMmU2N2Rm
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - secretRef:
          name: mysecret
  restartPolicy: Never
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret1
type: Opaque
data:
  USER_NAME: YWRtaW4xMjM0NQo=
  PASSWORD: MWYyZDFlMmU2N2Rm
